// providerStrings.js
//
// Translation dictionary for the provider-only language toggle (see
// PROVIDER_SIDE_CLEANUP_PLAN.md "Remaining work" section, and
// useProviderLang.jsx). Deliberately NOT app-wide — only consumed by
// provider-facing files listed in that plan. `bn` is the default and
// also acts as the fallback for any key missing from `en`.
//
// Key naming: <fileSlug>.<shortDescriptiveName>, camelCase. Grouped by
// file below so the audit is easy to re-check against each source file.

export const providerStrings = {
  bn: {
    // ---- ProviderDashboard.jsx ----
    'dashboard.title': 'প্রোভাইডার ড্যাশবোর্ড',
    'dashboard.verifiedBadge': 'ভেরিফায়েড সার্ভিস প্রোভাইডার',
    'dashboard.loading': 'লোড হচ্ছে…',
    'dashboard.setup.nameRequired': 'সার্ভিসের নাম দিন।',
    'dashboard.setup.saveError': 'সেভ করতে সমস্যা হয়েছে — আবার চেষ্টা করুন।',
    'dashboard.setup.title': 'আপনার সার্ভিস সেট আপ করুন',
    'dashboard.setup.subtitle': 'এটা একবারই করতে হবে। পরে সব কিছু এখান থেকে এডিট করতে পারবেন।',
    'dashboard.setup.category': 'ক্যাটাগরি',
    'dashboard.setup.serviceName': 'সার্ভিসের নাম',
    'dashboard.setup.serviceNamePlaceholder': "যেমন: Rafiq's Salon",
    'dashboard.setup.description': 'ডিটেইলস (ঐচ্ছিক)',
    'dashboard.setup.descriptionPlaceholder': 'সংক্ষেপে লিখুন',
    'dashboard.setup.saving': 'সেভ হচ্ছে…',
    'dashboard.setup.submit': 'সার্ভিস তৈরি করুন',
    'dashboard.shopOpen': 'দোকান খোলা আছে',
    'dashboard.shopClosed': 'দোকান বন্ধ আছে',
    'dashboard.shopOpen.hint': 'ট্যাপ করে বন্ধ করুন',
    'dashboard.shopClosed.hint': 'ট্যাপ করে খুলুন',
    'dashboard.dormant.title': 'এই শপ এখন নিষ্ক্রিয় (Dormant)',
    'dashboard.dormant.auto': 'অনেকদিন ধরে কোনো সার্ভিস চালু না থাকায় সিস্টেম নিজে থেকে এটা বন্ধ করে দিয়েছে।',
    'dashboard.dormant.manualTemporary': 'আপনি এই দোকান সাময়িকভাবে বন্ধ রেখেছেন — নিচে থেকে যেকোনো সময় আবার চালু করতে পারবেন।',
    'dashboard.dormant.manualPermanent': 'আপনি এই দোকান স্থায়ীভাবে বন্ধ করেছেন — নিজে থেকে আর চালু করা যাবে না, Founder-এর সাথে যোগাযোগ করুন।',
    'dashboard.dormant.visibility': 'ছাত্ররা এখনো তালিকায় দেখবে, তবে "বন্ধ আছে" নামের আলাদা অংশে।',
    'dashboard.pending.title': 'নতুন বুকিং অনুরোধ',
    'dashboard.pending.empty': 'নতুন কোনো বুকিং অনুরোধ নেই।',
    'dashboard.pending.conflictWarning': 'এই সময়ে আরেকটা বুকিং আগে থেকেই কনফার্ম করা আছে — আবার কনফার্ম করলে দুইটাই থেকে যাবে।',
    'dashboard.pending.confirmError': 'কনফার্ম করা যায়নি।',
    'dashboard.pending.cancelError': 'বাতিল করা যায়নি।',
    'dashboard.pending.requested': 'অনুরোধ করেছে:',
    'dashboard.pending.preferred': 'ছাত্র চেয়েছে:',
    'dashboard.pending.confirm': 'কনফার্ম করুন',
    'dashboard.pending.cancel': 'বাতিল করুন',
    'dashboard.pending.student': 'ছাত্র',
    'dashboard.pending.noShowSuffix': 'বার আসেনি',
    'dashboard.pending.noShowTitle': 'এই ছাত্র আগে বুকিং করেও একাধিকবার আসেনি',
    'dashboard.pending.unknownOffering': 'সার্ভিসের নাম নেই',
    'dashboard.inquiries.title': 'নতুন প্রশ্ন',
    'dashboard.inquiries.loading': 'লোড হচ্ছে…',
    'dashboard.inquiries.empty': 'নতুন কোনো প্রশ্ন নেই।',
    'dashboard.inquiries.answerError': 'উত্তর পাঠানো যায়নি।',
    'dashboard.inquiries.requested': 'জিজ্ঞেস করেছে:',
    'dashboard.inquiries.total': 'মোট দাম (আনুমানিক):',
    'dashboard.inquiries.replyPlaceholder': 'এখানে উত্তর লিখুন',
    'dashboard.inquiries.sending': 'পাঠানো হচ্ছে…',
    'dashboard.inquiries.reply': 'উত্তর দিন',
    'dashboard.inquiries.student': 'ছাত্র',
    'dashboard.confirmed.title': 'কনফার্ম করা বুকিং',
    'dashboard.confirmed.slot': 'সময়:',
    'dashboard.confirmed.at': '—',
    'dashboard.confirmed.priceLabel': 'কত টাকা নিয়েছেন',
    'dashboard.confirmed.finishConfirm': 'হ্যাঁ, হয়ে গেছে',
    'dashboard.confirmed.finish': 'কাজ শেষ',
    'dashboard.confirmed.noShow': 'ছাত্র আসেনি',
    'dashboard.confirmed.genericError': 'কিছু একটা সমস্যা হয়েছে।',
    'dashboard.confirmed.student': 'ছাত্র',


    // ---- ProviderDashboard.jsx Runner mode (Delivery/Errand Runner plan §4.3-§4.5) ----
    'dashboard.errand.openTitle': 'নতুন এরান্ড রিকোয়েস্ট',
    'dashboard.errand.openEmpty': 'এখন কোনো খোলা রিকোয়েস্ট নেই।',
    'dashboard.errand.acceptError': 'গ্রহণ করতে সমস্যা হয়েছে।',
    'dashboard.errand.requester': 'রিকোয়েস্টকারী',
    'dashboard.errand.requested': 'পাঠানো হয়েছে:',
    'dashboard.errand.targeted': 'আপনাকে নির্দিষ্টভাবে পাঠানো হয়েছে',
    'dashboard.errand.accept': 'গ্রহণ করুন',
    'dashboard.errand.accepting': 'গ্রহণ করা হচ্ছে…',
    'dashboard.errand.ongoingTitle': 'চলমান এরান্ড',
    'dashboard.errand.statusConfirmed': 'কনফার্ম হয়েছে',
    'dashboard.errand.statusAwaitingConfirm': 'রিকোয়েস্টকারীর কনফার্মেশনের অপেক্ষায়',
    'dashboard.errand.requesterPhone': 'রিকোয়েস্টকারীর ফোন নাম্বার:',
    'dashboard.errand.cancelAccept': 'বাতিল করুন',
    'dashboard.errand.finish': 'সম্পন্ন হয়েছে বলে মার্ক করুন',
    'dashboard.errand.genericError': 'সমস্যা হয়েছে।',

    // ---- ProviderMyShopHub.jsx ----
    'shopHub.title': 'আমার দোকান',
    'shopHub.subtitle': 'অফারিং, আয় ও শপের বিবরণ',
    'shopHub.loading': 'লোড হচ্ছে…',
    'shopHub.notSetUp': 'সেট করা হয়নি',
    'shopHub.noServiceYet': 'এখনো কোনো সার্ভিস সেট আপ করা হয়নি। ড্যাশবোর্ড থেকে সেট আপ করুন।',
    'shopHub.offeringsTitle': 'অফারিং ও আয়',
    'shopHub.itemsSuffix': (n) => `${n}টা আইটেম`,
    'shopHub.itemsWithRevenueSuffix': (n, revenue) => `${n}টা আইটেম · ৳${revenue} আয়`,
    'shopHub.settingsTitle': 'শপের বিবরণ ও স্ট্যাটাস',
    'shopHub.dormant': 'নিষ্ক্রিয়',
    'shopHub.active': 'সক্রিয়',

    // ---- ProviderOfferingsPage.jsx ----
    'offerings.backLink': 'আমার দোকান',
    'offerings.loading': 'লোড হচ্ছে…',
    'offerings.noServiceYet': 'এখনো কোনো সার্ভিস সেট আপ করা হয়নি।',
    'offerings.title': 'অফারিং',
    'offerings.itemCount': (n) => `${n}টা আইটেম`,
    'offerings.revenueTitle': 'মোট আয়',
    'offerings.revenueSubtitle': 'সম্পন্ন বুকিং থেকে',
    'offerings.saveError': 'সেভ করতে সমস্যা হয়েছে।',
    'offerings.empty': 'এখনো কোনো অফারিং যোগ করা হয়নি।',
    'offerings.maxImages': (max) => `প্রতি আইটেমে সর্বোচ্চ ${max}টা ছবি দেওয়া যাবে।`,
    'offerings.imageUploadError': 'ছবি আপলোড করতে সমস্যা হয়েছে।',
    'offerings.on': 'চালু',
    'offerings.off': 'বন্ধ',
    'offerings.noImage': 'ছবি নেই',
    'offerings.noPriceYet': 'দাম দেওয়া হয়নি',
    'offerings.perUnitHint': '(এক পিস/জনের দাম)',
    'offerings.pricePlaceholder': 'দাম (ঐচ্ছিক)',
    'offerings.newLabelPlaceholder': 'নতুন অফারিং (যেমন: হেয়ারকাট)',

    // ---- ProviderShopSettingsPage.jsx ----
    'shopSettings.backLink': 'আমার দোকান',
    'shopSettings.loading': 'লোড হচ্ছে…',
    'shopSettings.noServiceYet': 'এখনো কোনো সার্ভিস সেট আপ করা হয়নি।',
    'shopSettings.metaTitle': 'লোকেশন ও ডেলিভারি',
    'shopSettings.notSetUp': 'সেট করা হয়নি',
    'shopSettings.statusTitle': 'শপ স্ট্যাটাস',
    'shopSettings.dormant': 'নিষ্ক্রিয় (Dormant)',
    'shopSettings.active': 'সক্রিয়',
    'shopSettings.detailsTitle': 'সার্ভিস বিবরণ এডিট করুন',
    'shopSettings.coverLabel': 'কভার ছবি (সর্বোচ্চ 1MB)',
    'shopSettings.uploading': 'আপলোড হচ্ছে…',
    'shopSettings.changeCover': 'পরিবর্তন করুন',
    'shopSettings.uploadCover': 'ছবি আপলোড করুন',
    'shopSettings.removeCover': 'মুছুন',
    'shopSettings.coverRemoveError': 'মুছতে সমস্যা হয়েছে।',
    'shopSettings.imageUploadError': 'ছবি আপলোড করতে সমস্যা হয়েছে।',
    'shopSettings.locationLabel': 'লোকেশন (ঐচ্ছিক, ফ্রি-টেক্সট)',
    'shopSettings.locationPlaceholder': 'যেমন: Hall-3 Gate, Fazlul Haque Hall market',
    'shopSettings.deliveryLabel': 'হোম ডেলিভারি আছে',
    'shopSettings.saveError': 'সেভ করতে সমস্যা হয়েছে।',
    'shopSettings.saving': 'সেভ হচ্ছে…',
    'shopSettings.save': 'সেভ করুন',
    'shopSettings.saved': 'সেভ হয়েছে ✓',
    'shopSettings.statusUpdateError': 'আপডেট করতে সমস্যা হয়েছে — আবার চেষ্টা করুন।',
    'shopSettings.reactivating': 'হচ্ছে…',
    'shopSettings.reactivate': 'Reactivate — আবার সক্রিয় করুন',
    'shopSettings.permanentlyClosed': 'এই শপ স্থায়ীভাবে বন্ধ — নিজে থেকে reactivate করা যাবে না।',
    'shopSettings.deactivateIntro': 'Deactivate করলে শপ "নিষ্ক্রিয়" তালিকায় চলে যাবে — কিন্তু ডেটা/offerings সব অক্ষত থাকবে। কী ধরনের deactivate করবেন বেছে নিন:',
    'shopSettings.pauseOption': 'সাময়িক বিরতি (Temporary pause)',
    'shopSettings.permanentCloseOption': 'স্থায়ীভাবে বন্ধ (Permanent close)',
    'shopSettings.pauseConfirmText': 'Temporary pause করলে শপ নিষ্ক্রিয় তালিকায় যাবে, কিন্তু আপনি যেকোনো সময় নিজে থেকে আবার Reactivate করে ফিরিয়ে আনতে পারবেন। কোনো ডেটা মুছে যাবে না।',
    'shopSettings.pauseConfirmLabel': 'নিশ্চিত — Pause করুন',
    'shopSettings.permanentConfirmText': 'Permanent close করলে শপ নিষ্ক্রিয় তালিকায় যাবে এবং আপনি নিজে থেকে আর reactivate করতে পারবেন না — শুধু Founder-level review-এর মাধ্যমে আবার খোলা যাবে।',
    'shopSettings.permanentConfirmLabel': 'নিশ্চিত — স্থায়ীভাবে বন্ধ করুন',
    'shopSettings.cancel': 'বাতিল',
    'shopSettings.nameLabel': 'নাম',
    'shopSettings.descriptionLabel': 'ডিটেইলস',
    'shopSettings.priceNoteLabel': 'মূল্য নোট',
    'shopSettings.gpsSectionTitle': 'সঠিক লোকেশন (GPS)',
    'shopSettings.gpsNotSet': '📍 সঠিক শপ-লোকেশন এখনো যোগ করা হয়নি',
    'shopSettings.gpsSetAddButton': 'বর্তমান লোকেশন থেকে যোগ করুন',
    'shopSettings.gpsSetLabel': '📍 লোকেশন সেভ করা আছে ✓',
    'shopSettings.gpsUpdatedPrefix': 'শেষ আপডেট:',
    'shopSettings.gpsViewOnMaps': 'Google Maps-এ দেখুন',
    'shopSettings.gpsUpdateButton': 'আপডেট করুন',
    'shopSettings.gpsFetching': 'লোকেশন খোঁজা হচ্ছে…',
    'shopSettings.gpsUnsupported': 'এই ব্রাউজার লোকেশন সাপোর্ট করে না।',
    'shopSettings.gpsPermissionDenied': 'লোকেশন পারমিশন দেওয়া হয়নি — ব্রাউজার সেটিংস থেকে আবার চালু করতে পারেন।',
    'shopSettings.gpsPositionUnavailable': 'লোকেশন শনাক্ত করা যায়নি — আবার চেষ্টা করুন।',
    'shopSettings.gpsTimeout': 'লোকেশন খুঁজতে বেশি সময় লেগে যাচ্ছে — আবার চেষ্টা করুন।',
    'shopSettings.gpsGenericError': 'লোকেশন নিতে সমস্যা হয়েছে — আবার চেষ্টা করুন।',
    'shopSettings.gpsOutOfRange': 'এই কোঅর্ডিনেট বাংলাদেশের সীমার বাইরে মনে হচ্ছে — আবার চেষ্টা করুন।',
    'shopSettings.gpsLowAccuracyWarning': 'লোকেশন সঠিকভাবে শনাক্ত করা যায়নি, একটু খোলা জায়গায় গিয়ে আবার চেষ্টা করুন। চাইলে এই লোকেশন দিয়েই এগিয়ে যেতে পারেন।',
    'shopSettings.gpsRetryButton': 'আবার চেষ্টা করুন',
    'shopSettings.gpsProceedAnyway': 'তবুও এগিয়ে যান',
    'shopSettings.gpsConfirmTitle': 'নিশ্চিত করুন যে এই লোকেশনটাই আপনার শপের প্রকৃত অবস্থান',
    'shopSettings.gpsConfirmAccuracyPrefix': 'নির্ভুলতা (accuracy): আনুমানিক',
    'shopSettings.gpsConfirmAccuracySuffix': 'মিটার',
    'shopSettings.gpsConfirmYes': '✓ হ্যাঁ, এটাই সঠিক',
    'shopSettings.gpsConfirmRetry': '✗ আবার চেষ্টা করুন',
    'shopSettings.gpsSaveError': 'সেভ করতে সমস্যা হয়েছে — আবার চেষ্টা করুন।',
    'shopSettings.gpsDaysAgo': 'দিন আগে',
    'shopSettings.gpsToday': 'আজ',
    'shopSettings.gpsYesterday': 'গতকাল',

    // ---- ProviderVerificationPending.jsx ----
    'verify.resubmitMissingFields': 'নাম, ফোন নাম্বার এবং ঠিকানা — সবগুলো দিতে হবে।',
    'verify.resubmitMissingType': 'আপনার সার্ভিসের ধরনটি লিখুন।',
    'verify.resubmitError': 'আবার পাঠাতে সমস্যা হয়েছে — একটু পর চেষ্টা করুন।',
    'verify.pendingTitle': 'ভেরিফিকেশন অপেক্ষমান',
    'verify.pendingBody': 'আপনার সার্ভিস প্রোভাইডার একাউন্ট এখনো verify হয়নি। Founder সরাসরি যোগাযোগ করে আপনার একাউন্ট verify করবেন। verify হওয়ার পর এই পেজেই আপনার dashboard দেখতে পাবেন — কিছু করার দরকার নেই, শুধু অপেক্ষা করুন।',
    'verify.submittedInfoTitle': 'আপনার জমা দেওয়া তথ্য',
    'verify.nameLabel': 'নাম:',
    'verify.phoneLabel': 'ফোন:',
    'verify.serviceTypeLabel': 'সার্ভিসের ধরন:',
    'verify.serviceTypeOther': 'অন্যান্য',
    'verify.addressLabel': 'ঠিকানা:',
    'verify.contactFounder': 'যোগাযোগের জন্য Founder:',
    'verify.rejectedTitle': 'আপনার আবেদন গ্রহণ করা হয়নি',
    'verify.rejectedReasonLabel': 'কারণ:',
    'verify.rejectedNoReason': 'কোনো কারণ উল্লেখ করা হয়নি।',
    'verify.shopNameLabel': 'নাম / দোকানের নাম',
    'verify.phoneNumberLabel': 'ফোন নাম্বার',
    'verify.serviceTypeSelectLabel': 'সার্ভিসের ধরন',
    'verify.serviceTypeOtherLabel': 'সার্ভিসের ধরন লিখুন',
    'verify.shopAddressLabel': 'দোকানের ঠিকানা',
    'verify.resubmitting': 'পাঠানো হচ্ছে…',
    'verify.resubmit': 'আবার সাবমিট করুন',
    'verify.resubmittedDone': 'আপনার আবেদন আবার পাঠানো হয়েছে। Founder-এর যোগাযোগের অপেক্ষা করুন।',

    // ---- RequireProvider.jsx ----
    'requireProvider.checking': 'Provider access যাচাই করা হচ্ছে…',
    'requireProvider.accessRequiredTitle': 'Provider access প্রয়োজন',
    'requireProvider.accessRequiredBody': 'এই পেজটি শুধুমাত্র সার্ভিস প্রোভাইডার একাউন্টের জন্য।',
    'requireProvider.backHome': 'হোমে ফিরে যান',

    // ---- SidebarNavProvider.jsx ----
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.myShop': 'আমার দোকান',
    'nav.profile': 'প্রোফাইল',
    'nav.settings': 'সেটিংস',
    'nav.about': 'সম্পর্কে',
    'nav.groupProvider': 'প্রোভাইডার',
    'nav.groupAccount': 'একাউন্ট',

    // ---- ProviderHamburgerPanel.jsx ----
    'hamburger.notifications': 'নোটিফিকেশন',
    'hamburger.signOut': 'সাইন আউট',
    'hamburger.signingOut': 'সাইন আউট হচ্ছে…',
    'hamburger.signOutConfirm': 'সাইন আউট করবেন? এই ডিভাইসের ডেটা মুছে যাবে — যেকোনো সময় আবার লগইন করলে ক্লাউড থেকে সব ফিরে আসবে।',

    // ---- BottomNavProvider.js / BottomNav.jsx ----
    'bottomNav.dashboard': 'ড্যাশবোর্ড',
    'bottomNav.myShop': 'দোকান',
    'bottomNav.profile': 'প্রোফাইল',

    // ---- ProviderProfile.jsx ----
    'profile.loading': 'লোড হচ্ছে…',
    'profile.identityTitle': 'পরিচিতি',
    'profile.nameLabel': 'নাম',
    'profile.phoneLabel': 'ফোন',
    'profile.emailLabel': 'ইমেইল',
    'profile.statusVerified': 'ভেরিফায়েড সার্ভিস প্রোভাইডার',
    'profile.statusPending': 'ভেরিফিকেশন অপেক্ষমান',
    'profile.statusRejected': 'ভেরিফিকেশন প্রত্যাখ্যাত',
    'profile.changeCoverHint': 'ছবি পরিবর্তন করতে ট্যাপ করুন',
    'profile.coverAlt': 'শপ কভার',

    // ---- Settings.jsx (provider branch) ----
    'settings.title': 'সেটিংস',
    'settings.subtitle': 'থিম ও একাউন্ট',
    'settings.theme': 'থিম',
    'settings.account': 'একাউন্ট',
    'settings.signOutConfirm': 'সাইন আউট করবেন? এই ডিভাইসের ডেটা মুছে যাবে — যেকোনো সময় আবার লগইন করলে ক্লাউড থেকে সব ফিরে আসবে।',
    'settings.signOutSuccess': '✓ সাইন আউট হয়েছে। এই ডিভাইস ক্লিয়ার করা হয়েছে।',
    'settings.signOutFailed': '✗ সাইন আউট ব্যর্থ হয়েছে:',
    'settings.passwordResetSent': (email) => `✓ পাসওয়ার্ড রিসেট লিংক ${email}-এ পাঠানো হয়েছে। ইনবক্স চেক করুন।`,
    'settings.sending': 'পাঠানো হচ্ছে...',
    'settings.changePassword': 'পাসওয়ার্ড পরিবর্তন করুন',
    'settings.signingOut': 'সাইন আউট হচ্ছে...',
    'settings.signOut': 'সাইন আউট',
    'settings.defaultUser': 'ব্যবহারকারী',
    'settings.languageSectionLabel': 'ভাষা',

    // ---- About.jsx (provider branch) ----
    'about.body1': 'KUETx KUET শিক্ষার্থীদের বিশ্বস্ত লোকাল সার্ভিস প্রোভাইডারদের সাথে যুক্ত করে — সেলুন, খাবার, ফার্মেসি, স্টেশনারি এবং আরও অনেক কিছু — একই অ্যাপ থেকে যা তারা প্রতিদিন ব্যবহার করে।',
    'about.body2': 'আপনার প্রোভাইডার একাউন্ট নিয়ে কোনো প্রশ্ন আছে? আপনার Founder/Admin কনট্যাক্টের মাধ্যমে KUETx টিমের সাথে যোগাযোগ করুন।',

    // ---- ProviderNotifications.jsx ----
    'notifications.title': 'নোটিফিকেশন',
    'notifications.loading': 'লোড হচ্ছে…',
    'notifications.empty': 'এখনো কোনো নোটিফিকেশন নেই।',
    'notifications.fromFounder': 'ফাউন্ডার',
    'notifications.fromAdmin': 'অ্যাডমিন',
    'notifications.justForYou': 'শুধু আপনার জন্য',
  },

  en: {
    // ---- ProviderDashboard.jsx ----
    'dashboard.title': 'Provider Dashboard',
    'dashboard.verifiedBadge': 'Verified service provider',
    'dashboard.loading': 'Loading…',
    'dashboard.setup.nameRequired': 'Please enter a service name.',
    'dashboard.setup.saveError': 'Failed to save — please try again.',
    'dashboard.setup.title': 'Set up your service',
    'dashboard.setup.subtitle': "You'll only need to do this once. You can edit everything from here later.",
    'dashboard.setup.category': 'Category',
    'dashboard.setup.serviceName': 'Service name',
    'dashboard.setup.serviceNamePlaceholder': "e.g. Rafiq's Salon",
    'dashboard.setup.description': 'Description (optional)',
    'dashboard.setup.descriptionPlaceholder': 'Short description',
    'dashboard.setup.saving': 'Saving…',
    'dashboard.setup.submit': 'Create service',
    'dashboard.shopOpen': 'Shop is open',
    'dashboard.shopClosed': 'Shop is closed',
    'dashboard.shopOpen.hint': 'Tap to close',
    'dashboard.shopClosed.hint': 'Tap to open',
    'dashboard.dormant.title': 'This shop is dormant',
    'dashboard.dormant.auto': 'No service was open for a long time, so the system turned this shop off.',
    'dashboard.dormant.manualTemporary': 'You paused this shop — you can turn it back on anytime below.',
    'dashboard.dormant.manualPermanent': 'You closed this shop for good — you can\'t turn it back on yourself; contact the Founder.',
    'dashboard.dormant.visibility': 'Students still see it in the list, but in a separate "closed" section.',
    'dashboard.pending.title': 'New booking requests',
    'dashboard.pending.empty': 'No new booking requests.',
    'dashboard.pending.conflictWarning': 'Another booking is already confirmed for this time — confirming this one too will keep both.',
    'dashboard.pending.confirmError': 'Could not confirm.',
    'dashboard.pending.cancelError': 'Could not cancel.',
    'dashboard.pending.requested': 'Asked for:',
    'dashboard.pending.preferred': 'Student wants:',
    'dashboard.pending.confirm': 'Confirm',
    'dashboard.pending.cancel': 'Cancel',
    'dashboard.pending.student': 'Student',
    'dashboard.pending.noShowSuffix': 'no-shows before',
    'dashboard.pending.noShowTitle': 'This student has missed bookings here before',
    'dashboard.pending.unknownOffering': 'No service name',
    'dashboard.inquiries.title': 'New questions',
    'dashboard.inquiries.loading': 'Loading…',
    'dashboard.inquiries.empty': 'No new questions.',
    'dashboard.inquiries.answerError': 'Could not send reply.',
    'dashboard.inquiries.requested': 'Asked:',
    'dashboard.inquiries.total': 'Estimated total:',
    'dashboard.inquiries.replyPlaceholder': 'Type your reply',
    'dashboard.inquiries.sending': 'Sending…',
    'dashboard.inquiries.reply': 'Reply',
    'dashboard.inquiries.student': 'Student',
    'dashboard.confirmed.title': 'Confirmed bookings',
    'dashboard.confirmed.slot': 'Time:',
    'dashboard.confirmed.at': '—',
    'dashboard.confirmed.priceLabel': 'Amount charged',
    'dashboard.confirmed.finishConfirm': 'Yes, it\'s done',
    'dashboard.confirmed.finish': 'Job done',
    'dashboard.confirmed.noShow': 'Student didn\'t show',
    'dashboard.confirmed.genericError': 'Something went wrong.',
    'dashboard.confirmed.student': 'Student',

    // ---- ProviderDashboard.jsx Runner mode (Delivery/Errand Runner plan §4.3-§4.5) ----
    'dashboard.errand.openTitle': 'New Errand Requests',
    'dashboard.errand.openEmpty': 'No open requests right now.',
    'dashboard.errand.acceptError': 'Failed to accept.',
    'dashboard.errand.requester': 'Requester',
    'dashboard.errand.requested': 'Requested:',
    'dashboard.errand.targeted': 'Sent to you specifically',
    'dashboard.errand.accept': 'Accept',
    'dashboard.errand.accepting': 'Accepting…',
    'dashboard.errand.ongoingTitle': 'Ongoing Errands',
    'dashboard.errand.statusConfirmed': 'Confirmed',
    'dashboard.errand.statusAwaitingConfirm': 'Awaiting requester confirmation',
    'dashboard.errand.requesterPhone': "Requester's phone:",
    'dashboard.errand.cancelAccept': 'Cancel',
    'dashboard.errand.finish': 'Mark as finished',
    'dashboard.errand.genericError': 'Something went wrong.',

    // ---- ProviderMyShopHub.jsx ----
    'shopHub.title': 'My Shop',
    'shopHub.subtitle': 'Offerings, earnings, and shop details',
    'shopHub.loading': 'Loading…',
    'shopHub.notSetUp': 'Not set up',
    'shopHub.noServiceYet': "You haven't set up a service yet. Set one up from Dashboard.",
    'shopHub.offeringsTitle': 'Offerings & Earnings',
    'shopHub.itemsSuffix': (n) => `${n} item${n === 1 ? '' : 's'}`,
    'shopHub.itemsWithRevenueSuffix': (n, revenue) => `${n} item${n === 1 ? '' : 's'} · ৳${revenue} earned`,
    'shopHub.settingsTitle': 'Shop Details & Status',
    'shopHub.dormant': 'Dormant',
    'shopHub.active': 'Active',

    // ---- ProviderOfferingsPage.jsx ----
    'offerings.backLink': 'My Shop',
    'offerings.loading': 'Loading…',
    'offerings.noServiceYet': "You haven't set up a service yet.",
    'offerings.title': 'Offerings',
    'offerings.itemCount': (n) => `${n} item${n === 1 ? '' : 's'}`,
    'offerings.revenueTitle': 'Total earnings',
    'offerings.revenueSubtitle': 'From completed bookings',
    'offerings.saveError': 'Failed to save.',
    'offerings.empty': "You haven't added any offerings yet.",
    'offerings.maxImages': (max) => `You can add up to ${max} images per item.`,
    'offerings.imageUploadError': 'Failed to upload image.',
    'offerings.on': 'ON',
    'offerings.off': 'OFF',
    'offerings.noImage': 'No photo',
    'offerings.noPriceYet': 'No price set',
    'offerings.perUnitHint': '(price per piece/person)',
    'offerings.pricePlaceholder': 'Price (optional)',
    'offerings.newLabelPlaceholder': 'New offering (e.g. Haircut)',

    // ---- ProviderShopSettingsPage.jsx ----
    'shopSettings.backLink': 'My Shop',
    'shopSettings.loading': 'Loading…',
    'shopSettings.noServiceYet': "You haven't set up a service yet.",
    'shopSettings.metaTitle': 'Location & delivery',
    'shopSettings.notSetUp': 'Not set up',
    'shopSettings.statusTitle': 'Shop status',
    'shopSettings.dormant': 'Dormant',
    'shopSettings.active': 'Active',
    'shopSettings.detailsTitle': 'Edit service details',
    'shopSettings.coverLabel': 'Cover image (max 1MB)',
    'shopSettings.uploading': 'Uploading…',
    'shopSettings.changeCover': 'Change',
    'shopSettings.uploadCover': 'Upload image',
    'shopSettings.removeCover': 'Remove',
    'shopSettings.coverRemoveError': 'Failed to remove.',
    'shopSettings.imageUploadError': 'Failed to upload image.',
    'shopSettings.locationLabel': 'Location (optional, free text)',
    'shopSettings.locationPlaceholder': 'e.g. Hall-3 Gate, Fazlul Haque Hall market',
    'shopSettings.deliveryLabel': 'Home delivery available',
    'shopSettings.saveError': 'Failed to save.',
    'shopSettings.saving': 'Saving…',
    'shopSettings.save': 'Save',
    'shopSettings.saved': 'Saved ✓',
    'shopSettings.statusUpdateError': 'Failed to update — please try again.',
    'shopSettings.reactivating': 'Working…',
    'shopSettings.reactivate': 'Reactivate — make active again',
    'shopSettings.permanentlyClosed': "This shop is permanently closed — it can't be reactivated on your own.",
    'shopSettings.deactivateIntro': 'Deactivating moves your shop to the "Dormant" list — but all your data and offerings stay intact. Choose how you\'d like to deactivate:',
    'shopSettings.pauseOption': 'Temporary pause',
    'shopSettings.permanentCloseOption': 'Permanent close',
    'shopSettings.pauseConfirmText': "A temporary pause moves your shop to the dormant list, but you can reactivate it yourself anytime. No data will be lost.",
    'shopSettings.pauseConfirmLabel': 'Confirm — Pause',
    'shopSettings.permanentConfirmText': "A permanent close moves your shop to the dormant list and you won't be able to reactivate it yourself — it can only be reopened through Founder-level review.",
    'shopSettings.permanentConfirmLabel': 'Confirm — Close permanently',
    'shopSettings.cancel': 'Cancel',
    'shopSettings.nameLabel': 'Name',
    'shopSettings.descriptionLabel': 'Description',
    'shopSettings.priceNoteLabel': 'Price note',
    'shopSettings.gpsSectionTitle': 'Exact location (GPS)',
    'shopSettings.gpsNotSet': "📍 Exact shop location hasn't been added yet",
    'shopSettings.gpsSetAddButton': 'Add from current location',
    'shopSettings.gpsSetLabel': '📍 Location saved ✓',
    'shopSettings.gpsUpdatedPrefix': 'Last updated:',
    'shopSettings.gpsViewOnMaps': 'View on Google Maps',
    'shopSettings.gpsUpdateButton': 'Update',
    'shopSettings.gpsFetching': 'Finding location…',
    'shopSettings.gpsUnsupported': "This browser doesn't support location.",
    'shopSettings.gpsPermissionDenied': "Location permission wasn't granted — you can re-enable it from browser settings.",
    'shopSettings.gpsPositionUnavailable': "Couldn't detect location — please try again.",
    'shopSettings.gpsTimeout': "Finding location is taking too long — please try again.",
    'shopSettings.gpsGenericError': 'There was a problem getting your location — please try again.',
    'shopSettings.gpsOutOfRange': 'This coordinate looks outside Bangladesh — please try again.',
    'shopSettings.gpsLowAccuracyWarning': "Location couldn't be pinpointed accurately — try again from a more open area. You can also proceed with this location anyway.",
    'shopSettings.gpsRetryButton': 'Try again',
    'shopSettings.gpsProceedAnyway': 'Proceed anyway',
    'shopSettings.gpsConfirmTitle': "Confirm that this is your shop's actual location",
    'shopSettings.gpsConfirmAccuracyPrefix': 'Accuracy: approx.',
    'shopSettings.gpsConfirmAccuracySuffix': 'meters',
    'shopSettings.gpsConfirmYes': '✓ Yes, this is correct',
    'shopSettings.gpsConfirmRetry': '✗ Try again',
    'shopSettings.gpsSaveError': 'Failed to save — please try again.',
    'shopSettings.gpsDaysAgo': 'days ago',
    'shopSettings.gpsToday': 'today',
    'shopSettings.gpsYesterday': 'yesterday',

    // ---- ProviderVerificationPending.jsx ----
    'verify.resubmitMissingFields': 'Please fill in your name, phone number, and address — all are required.',
    'verify.resubmitMissingType': 'Please describe your service type.',
    'verify.resubmitError': 'Failed to resend — please try again shortly.',
    'verify.pendingTitle': 'Verification pending',
    'verify.pendingBody': "Your service provider account hasn't been verified yet. The Founder will contact you directly to verify your account. Once verified, you'll see your dashboard right on this page — there's nothing you need to do, just wait.",
    'verify.submittedInfoTitle': 'What you submitted',
    'verify.nameLabel': 'Name:',
    'verify.phoneLabel': 'Phone:',
    'verify.serviceTypeLabel': 'Service type:',
    'verify.serviceTypeOther': 'Other',
    'verify.addressLabel': 'Address:',
    'verify.contactFounder': 'Contact the Founder:',
    'verify.rejectedTitle': 'Your application was not approved',
    'verify.rejectedReasonLabel': 'Reason:',
    'verify.rejectedNoReason': 'No reason was given.',
    'verify.shopNameLabel': 'Name / Shop name',
    'verify.phoneNumberLabel': 'Phone number',
    'verify.serviceTypeSelectLabel': 'Service type',
    'verify.serviceTypeOtherLabel': 'Describe your service type',
    'verify.shopAddressLabel': 'Shop address',
    'verify.resubmitting': 'Sending…',
    'verify.resubmit': 'Resubmit',
    'verify.resubmittedDone': 'Your application has been resubmitted. Please wait for the Founder to reach out.',

    // ---- RequireProvider.jsx ----
    'requireProvider.checking': 'Checking provider access…',
    'requireProvider.accessRequiredTitle': 'Provider access required',
    'requireProvider.accessRequiredBody': 'This page is only available to service provider accounts.',
    'requireProvider.backHome': 'Back to home',

    // ---- SidebarNavProvider.jsx ----
    'nav.dashboard': 'Dashboard',
    'nav.myShop': 'My Shop',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.about': 'About',
    'nav.groupProvider': 'Provider',
    'nav.groupAccount': 'Account',

    // ---- ProviderHamburgerPanel.jsx ----
    'hamburger.notifications': 'Notifications',
    'hamburger.signOut': 'Sign Out',
    'hamburger.signingOut': 'Signing out…',
    'hamburger.signOutConfirm': 'Sign out? This device will be cleared — log back in anytime and everything comes right back from the cloud.',

    // ---- BottomNavProvider.js / BottomNav.jsx ----
    'bottomNav.dashboard': 'Dashboard',
    'bottomNav.myShop': 'My Shop',
    'bottomNav.profile': 'Profile',

    // ---- ProviderProfile.jsx ----
    'profile.loading': 'Loading…',
    'profile.identityTitle': 'Identity',
    'profile.nameLabel': 'Name',
    'profile.phoneLabel': 'Phone',
    'profile.emailLabel': 'Email',
    'profile.statusVerified': 'Verified service provider',
    'profile.statusPending': 'Verification pending',
    'profile.statusRejected': 'Verification rejected',
    'profile.changeCoverHint': 'Tap to change photo',
    'profile.coverAlt': 'Shop cover',

    // ---- Settings.jsx (provider branch) ----
    'settings.title': 'Settings',
    'settings.subtitle': 'Theme and account',
    'settings.theme': 'Theme',
    'settings.account': 'Account',
    'settings.signOutConfirm': 'Sign out? This device will be cleared — log back in anytime and everything comes right back from the cloud.',
    'settings.signOutSuccess': '✓ Signed out. This device has been cleared.',
    'settings.signOutFailed': '✗ Sign out failed:',
    'settings.passwordResetSent': (email) => `✓ A password reset link was sent to ${email}. Check your inbox.`,
    'settings.sending': 'Sending...',
    'settings.changePassword': 'Change password',
    'settings.signingOut': 'Signing out...',
    'settings.signOut': 'Sign Out',
    'settings.defaultUser': 'User',
    'settings.languageSectionLabel': 'Language',

    // ---- About.jsx (provider branch) ----
    'about.body1': 'KUETx connects KUET students with trusted local service providers — salons, food, pharmacy, stationery, and more — right from the app they already use every day.',
    'about.body2': 'Questions about your provider account? Reach out to the KUETx team through your Founder/Admin contact.',

    // ---- ProviderNotifications.jsx ----
    'notifications.title': 'Notifications',
    'notifications.loading': 'Loading…',
    'notifications.empty': 'No notifications yet.',
    'notifications.fromFounder': 'Founder',
    'notifications.fromAdmin': 'Admin',
    'notifications.justForYou': 'Just for you',
  },
};
