const fs = require('fs');
const path = require('path');

const inputPath = path.resolve('samplesourcejustforreference/archcurriculumn.json');
const outputRoot = path.resolve('src/data/curriculum/departments/Arch');
const termsDir = path.join(outputRoot, 'terms');
const syllabusDir = path.join(outputRoot, 'syllabus');
const termOrder = ['Y1T1', 'Y1T2', 'Y2T1', 'Y2T2', 'Y3T1', 'Y3T2', 'Y4T1', 'Y4T2'];
const PLACEHOLDER = 'Sorry, we cannot collect only this dept course syllabus. Please help us and contact with founder.';

const ensureDir = dir => fs.mkdirSync(dir, { recursive: true });
const writeFile = (filePath, content) => fs.writeFileSync(filePath, content, 'utf8');
const readJson = input => JSON.parse(fs.readFileSync(input, 'utf8'));

const normalizeContactHours = value => {
  if (value === undefined || value === null || value === '') {
    return null;
  }
  return String(value).replace(/hrs\/wk/gi, 'hrs/week');
};

const normalizeCredit = value => {
  if (value === undefined || value === null || value === '') {
    return null;
  }
  const num = Number(value);
  return Number.isFinite(num) ? num : value;
};

const isSessionalCourse = course => {
  const title = String(course.title || '').toLowerCase();
  if (course.sessionalNote) {
    return true;
  }
  if (typeof course.credit === 'number' && course.credit <= 1.5) {
    return true;
  }
  return ['sessional', 'laboratory', 'lab', 'drawing', 'project', 'seminar', 'workshop'].some(keyword => title.includes(keyword));
};

const makeMeta = data => ({
  code: 'Arch',
  name: 'Architecture',
  acronym: 'Arch',
  university: data.university || 'Khulna University of Engineering & Technology',
  effectiveFrom: data.effectiveFrom || '2015-2016',
});

const makeNotes = data => ({
  overview: 'Arch curriculum generated from provided JSON reference with placeholder syllabi for each course.',
  source: 'samplesourcejustforreference/archcurriculumn.json',
  effectiveFrom: data.effectiveFrom || '2015-2016',
});

const makeOptionalCourses = data => {
  const groups = data.optionalGroups || {};
  return Object.values(groups).map(course => ({
    code: course.courseCode,
    title: course.title,
    credits: normalizeCredit(course.credit),
    contactHours: normalizeContactHours(course.contactHour),
    type: isSessionalCourse(course) ? 'Sessional' : 'Theory',
    isOptional: true,
  }));
};

const makeTermCourses = courses => Object.entries(courses || {}).map(([code, course]) => ({
  code,
  title: course.title,
  credits: normalizeCredit(course.credit),
  contactHours: normalizeContactHours(course.contactHour),
  type: isSessionalCourse(course) ? 'Sessional' : 'Theory',
  isOptional: false,
}));

const makeSyllabusCourses = courses => {
  const result = {};
  Object.entries(courses || {}).forEach(([code, course]) => {
    result[code] = {
      title: course.title,
      credit: normalizeCredit(course.credit),
      contactHour: normalizeContactHours(course.contactHour),
      topics: [PLACEHOLDER],
      sessionalNote: course.sessionalNote ?? null,
      references: [],
    };
  });
  return result;
};

const makeTermsIndex = termKeys => {
  const imports = termKeys.map(termKey => `import { ${termKey} } from './${termKey}.js';`).join('\n');
  const entries = termKeys.map(termKey => `  ${termKey},`).join('\n');
  return `${imports}\n\nexport const Arch_TERMS = {\n${entries}\n};\n\nexport default Arch_TERMS;\n`;
};

const makeSyllabusIndex = termKeys => {
  const imports = termKeys.map(termKey => `import { Arch_SYLLABUS_${termKey} } from './${termKey}.js';`).join('\n');
  const entries = termKeys.map(termKey => `  ${termKey}: Arch_SYLLABUS_${termKey},`).join('\n');
  return `// AUTO-GENERATED by scripts/generate_arch_from_json.cjs\n${imports}\n\nconst TERM_SYLLABUS = {\n${entries}\n};\n\nconst mergeCourses = () => {\n  const all = {};\n  Object.values(TERM_SYLLABUS).forEach(term => { Object.assign(all, term.courses); });\n  return all;\n};\n\nexport const Arch_SYLLABUS = {\n  sourceFile: 'src/data/curriculum/departments/Arch/syllabus/index.js',\n  terms: TERM_SYLLABUS,\n  courses: mergeCourses(),\n};\n\nexport default Arch_SYLLABUS;\n`;
};

const makeDepartmentIndex = () => (
  `import { Arch_META } from './meta.js';\n` +
  `import { Arch_TERMS } from './terms/index.js';\n` +
  `import { Arch_OPTIONAL_COURSES } from './optional.js';\n` +
  `import { Arch_NOTES } from './notes.js';\n` +
  `import { Arch_SYLLABUS } from './syllabus/index.js';\n\n` +
  `export const Arch_DEPARTMENT = {\n` +
  `  meta: Arch_META,\n` +
  `  terms: Arch_TERMS,\n` +
  `  optional: Arch_OPTIONAL_COURSES,\n` +
  `  notes: Arch_NOTES,\n` +
  `  syllabus: Arch_SYLLABUS,\n` +
  `};\n\nexport default Arch_DEPARTMENT;\n`
);

const main = () => {
  const data = readJson(inputPath);
  const termsData = data.terms || {};
  const optionalCourses = makeOptionalCourses(data);

  ensureDir(outputRoot);
  ensureDir(termsDir);
  ensureDir(syllabusDir);

  writeFile(path.join(outputRoot, 'meta.js'), `export const Arch_META = ${JSON.stringify(makeMeta(data), null, 2)};\n\nexport default Arch_META;\n`);
  writeFile(path.join(outputRoot, 'notes.js'), `export const Arch_NOTES = ${JSON.stringify(makeNotes(data), null, 2)};\n\nexport default Arch_NOTES;\n`);
  writeFile(path.join(outputRoot, 'optional.js'), `export const Arch_OPTIONAL_COURSES = ${JSON.stringify(optionalCourses, null, 2)};\n\nexport default Arch_OPTIONAL_COURSES;\n`);
  writeFile(path.join(outputRoot, 'index.js'), makeDepartmentIndex());

  termOrder.forEach(termKey => {
    const term = termsData[termKey];
    if (!term) {
      return;
    }

    writeFile(
      path.join(termsDir, `${termKey}.js`),
      `export const ${termKey} = ${JSON.stringify(makeTermCourses(term.courses || {}), null, 2)};\n\nexport default ${termKey};\n`
    );

    const syllabusTerm = {
      termKey: term.termKey,
      title: term.title,
      courses: makeSyllabusCourses(term.courses || {}),
      optionalCourses: Array.isArray(term.optionalCourses) ? term.optionalCourses : [],
      termNotes: Array.isArray(term.termNotes) ? term.termNotes : [],
    };

    writeFile(
      path.join(syllabusDir, `${termKey}.js`),
      `export const Arch_SYLLABUS_${termKey} = ${JSON.stringify(syllabusTerm, null, 2)};\n\nexport default Arch_SYLLABUS_${termKey};\n`
    );
  });

  writeFile(path.join(termsDir, 'index.js'), makeTermsIndex(termOrder));
  writeFile(path.join(syllabusDir, 'index.js'), makeSyllabusIndex(termOrder));

  console.log('Arch curriculum generated successfully.');
};

main();
