const fs = require('fs');
const path = require('path');

const termOrder = ['Y1T1', 'Y1T2', 'Y2T1', 'Y2T2', 'Y3T1', 'Y3T2', 'Y4T1', 'Y4T2'];

const normalizeContactHours = value => {
  if (!value) {
    return value;
  }
  return String(value).replace(/hrs\/wk/g, 'hrs/week');
};

const normalizeCredit = value => {
  if (value === null || value === undefined) {
    return null;
  }
  const num = Number(value);
  return Number.isFinite(num) ? num : value;
};

const isSessionalCourse = course => {
  const title = String(course.title || '').toLowerCase();
  const keywords = [
    'lab',
    'laboratory',
    'sessional',
    'workshop',
    'practice',
    'practices',
    'drawing',
    'project',
    'thesis',
    'training',
    'seminar',
    'attachment'
  ];

  if (keywords.some(keyword => title.includes(keyword))) {
    return true;
  }

  const credit = course.credit;
  if (typeof credit === 'number' && credit <= 1.5) {
    return true;
  }

  const contact = String(course.contactHour || '');
  if (contact.includes('3/2')) {
    return true;
  }

  return false;
};

const readJson = inputPath => JSON.parse(fs.readFileSync(inputPath, 'utf8'));
const ensureDir = dirPath => fs.mkdirSync(dirPath, { recursive: true });
const writeFile = (filePath, content) => fs.writeFileSync(filePath, content, 'utf8');

const buildTermsArray = courses => Object.entries(courses).map(([code, course]) => ({
  code,
  title: course.title,
  credits: normalizeCredit(course.credit),
  contactHours: normalizeContactHours(course.contactHour || null),
  type: isSessionalCourse(course) ? 'Sessional' : 'Theory',
  isOptional: false,
}));

const buildSyllabusTerm = term => {
  const normalizedCourses = {};
  Object.entries(term.courses || {}).forEach(([code, course]) => {
    normalizedCourses[code] = {
      title: course.title,
      credit: normalizeCredit(course.credit),
      contactHour: normalizeContactHours(course.contactHour || null),
      topics: Array.isArray(course.topics) ? course.topics : [],
      sessionalNote: course.sessionalNote ?? null,
      references: Array.isArray(course.references) ? course.references : [],
    };
  });

  return {
    termKey: term.termKey,
    title: term.title,
    courses: normalizedCourses,
    optionalCourses: Array.isArray(term.optionalCourses) ? term.optionalCourses : [],
    termNotes: Array.isArray(term.termNotes) ? term.termNotes : [],
  };
};

const buildOptionalCourses = terms => {
  const seen = new Map();
  Object.entries(terms || {}).forEach(([termKey, term]) => {
    const groups = term.optionalGroups || {};
    Object.entries(groups).forEach(([groupName, courses]) => {
      (courses || []).forEach(course => {
        const code = course.courseCode;
        if (!code || seen.has(code)) {
          return;
        }
        seen.set(code, {
          code,
          title: course.title,
          credits: normalizeCredit(course.credit),
          contactHours: normalizeContactHours(course.contactHour || null),
          type: isSessionalCourse(course) ? 'Sessional' : 'Theory',
          group: groupName,
          term: termKey,
          topics: Array.isArray(course.topics) ? course.topics : [],
          sessionalNote: course.sessionalNote ?? null,
          references: Array.isArray(course.references) ? course.references : [],
          isOptional: true,
        });
      });
    });
  });
  return Array.from(seen.values());
};

const buildOptionalGroups = terms => {
  const grouped = {};
  Object.values(terms || {}).forEach(term => {
    Object.entries(term.optionalGroups || {}).forEach(([groupName, courses]) => {
      if (!grouped[groupName]) {
        grouped[groupName] = [];
      }
      (courses || []).forEach(course => {
        grouped[groupName].push({
          code: course.courseCode,
          title: course.title,
          credit: normalizeCredit(course.credit),
          contactHour: normalizeContactHours(course.contactHour || null),
          topics: Array.isArray(course.topics) ? course.topics : [],
          sessionalNote: course.sessionalNote ?? null,
          references: Array.isArray(course.references) ? course.references : [],
        });
      });
    });
  });
  return grouped;
};

const makeSyllabusIndex = termKeys => {
  const imports = termKeys.map(termKey => `import { TE_SYLLABUS_${termKey} } from './${termKey}.js';`).join('\n');
  const termEntries = termKeys.map(termKey => `  ${termKey}: TE_SYLLABUS_${termKey},`).join('\n');

  return `// AUTO-GENERATED by scripts/generate_te_from_json.cjs\n${imports}\n\nconst TERM_SYLLABUS = {\n${termEntries}\n};\n\nconst mergeCourses = () => {\n  const all = {};\n  Object.values(TERM_SYLLABUS).forEach(term => { Object.assign(all, term.courses); });\n  return all;\n};\n\nexport const TE_SYLLABUS = {\n  sourceFile: 'src/data/curriculum/departments/TE/syllabus/index.js',\n  terms: TERM_SYLLABUS,\n  courses: mergeCourses(),\n};\n\nexport default TE_SYLLABUS;\n`;
};

const makeTermsIndex = termKeys => {
  const imports = termKeys.map(termKey => `import { ${termKey} } from './${termKey}.js';`).join('\n');
  const entries = termKeys.map(termKey => `  ${termKey},`).join('\n');
  return `${imports}\n\nexport const TE_TERMS = {\n${entries}\n};\n\nexport default TE_TERMS;\n`;
};

const makeDepartmentIndex = () => (
  `import { TE_META } from './meta.js';\n` +
  `import { TE_TERMS } from './terms/index.js';\n` +
  `import { TE_OPTIONAL_COURSES } from './optional.js';\n` +
  `import { TE_NOTES } from './notes.js';\n` +
  `import { TE_SYLLABUS } from './syllabus/index.js';\n\n` +
  `export const TE_DEPARTMENT = {\n` +
  `  meta: TE_META,\n` +
  `  terms: TE_TERMS,\n` +
  `  optional: TE_OPTIONAL_COURSES,\n` +
  `  notes: TE_NOTES,\n` +
  `  syllabus: TE_SYLLABUS,\n` +
  `};\n\n` +
  `export default TE_DEPARTMENT;\n`
);

const makeTermSource = term => {
  const entries = Object.entries(term.courses || {}).map(([code, course]) => `  ${JSON.stringify(code)}: ${JSON.stringify({
    title: course.title,
    credit: normalizeCredit(course.credit),
    contactHour: normalizeContactHours(course.contactHour || null),
    topics: Array.isArray(course.topics) ? course.topics : [],
    sessionalNote: course.sessionalNote ?? null,
    references: Array.isArray(course.references) ? course.references : [],
  }, null, 2)},`).join('\n');

  return `export const TE_SYLLABUS_${term.termKey} = {\n  termKey: ${JSON.stringify(term.termKey)},\n  title: ${JSON.stringify(term.title)},\n  courses: {\n${entries}\n  },\n  optionalCourses: ${JSON.stringify(Array.isArray(term.optionalCourses) ? term.optionalCourses : [], null, 2)},\n  termNotes: ${JSON.stringify(Array.isArray(term.termNotes) ? term.termNotes : [], null, 2)},\n};\n\nexport default TE_SYLLABUS_${term.termKey};\n`;
};

const makeTermSummarySource = term => {
  const entries = Object.entries(term.courses || {}).map(([code, course]) => `  ${JSON.stringify(code)}: ${JSON.stringify({
    title: course.title,
    credit: normalizeCredit(course.credit),
    contactHour: normalizeContactHours(course.contactHour || null),
    topics: Array.isArray(course.topics) ? course.topics : [],
    sessionalNote: course.sessionalNote ?? null,
    references: Array.isArray(course.references) ? course.references : [],
  }, null, 2)},`).join('\n');

  return `export const ${term.termKey} = [\n${Object.entries(term.courses || {}).map(([code, course]) => `  ${JSON.stringify({
    code,
    title: course.title,
    credits: normalizeCredit(course.credit),
    contactHours: normalizeContactHours(course.contactHour || null),
    type: isSessionalCourse(course) ? 'Sessional' : 'Theory',
    isOptional: false,
  }, null, 2)},`).join('\n')}\n];\n\nexport default ${term.termKey};\n`;
};

const main = () => {
  const inputPath = path.resolve('samplesourcejustforreference/tecurriculm.json');
  const data = readJson(inputPath);
  const terms = data.terms || {};

  const outputRoot = path.resolve('src/data/curriculum/departments/TE');
  const termsDir = path.join(outputRoot, 'terms');
  const syllabusDir = path.join(outputRoot, 'syllabus');

  ensureDir(termsDir);
  ensureDir(syllabusDir);

  const meta = {
    code: 'TE',
    name: 'Textile Engineering',
    acronym: 'TE',
    university: 'Khulna University of Engineering & Technology',
  };

  const notes = {
    overview: 'TE syllabus generated from provided JSON source.',
    source: 'samplesourcejustforreference/tecurriculm.json',
    effectiveFrom: data.effectiveFrom || '2015-2016',
  };

  const optionalCourses = buildOptionalCourses(terms);
  const optionalGroups = buildOptionalGroups(terms);

  writeFile(path.join(outputRoot, 'meta.js'), `export const TE_META = ${JSON.stringify(meta, null, 2)};\nexport default TE_META;\n`);
  writeFile(path.join(outputRoot, 'notes.js'), `export const TE_NOTES = ${JSON.stringify(notes, null, 2)};\nexport default TE_NOTES;\n`);
  writeFile(path.join(outputRoot, 'optional.js'), `export const TE_OPTIONAL_COURSES = ${JSON.stringify(optionalCourses, null, 2)};\nexport default TE_OPTIONAL_COURSES;\n`);
  writeFile(path.join(outputRoot, 'index.js'), makeDepartmentIndex());

  termOrder.forEach(termKey => {
    const term = terms[termKey];
    if (!term) {
      return;
    }

    writeFile(path.join(termsDir, `${termKey}.js`), makeTermSummarySource(term));
    writeFile(path.join(syllabusDir, `${termKey}.js`), makeTermSource(term));
  });

  writeFile(path.join(termsDir, 'index.js'), makeTermsIndex(termOrder));
  writeFile(path.join(syllabusDir, 'index.js'), makeSyllabusIndex(termOrder));
  writeFile(path.join(syllabusDir, 'optional.js'), `export const TE_SYLLABUS_OPTIONAL_GROUPS = ${JSON.stringify(optionalGroups, null, 2)};\nexport default TE_SYLLABUS_OPTIONAL_GROUPS;\n`);
};

main();
