#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const repoRoot = path.resolve(__dirname, '..');
const jsonPath = path.join(repoRoot, 'ECEcuriculumn.json');
const outDir = path.join(repoRoot, 'src', 'data', 'curriculum', 'departments', 'ECE', 'syllabus');

if (!fs.existsSync(jsonPath)) {
  console.error('ECEcuriculumn.json not found at', jsonPath);
  process.exit(1);
}
const raw = fs.readFileSync(jsonPath, 'utf8');
const data = JSON.parse(raw);
const terms = data.terms || {};

if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

const termKeys = Object.keys(terms);
const uniqueCodes = new Set();
for (const key of termKeys) {
  const term = terms[key];
  // create a shallow copy and ensure courses is an object
  const mergedTerm = { ...term, courses: { ...(term.courses || {}) } };
  // if optionalCourses exist as an array, merge them into courses by their courseCode
  if (Array.isArray(term.optionalCourses)) {
    term.optionalCourses.forEach(item => {
      const code = item.courseCode || item.code || item.title || null;
      if (code) mergedTerm.courses[code] = { ...item, code: item.courseCode || item.code };
    });
  }

  const varName = `ECE_SYLLABUS_${key}`;
  const fileName = path.join(outDir, `${key}.js`);
  const fileContent = `export const ${varName} = ${JSON.stringify(mergedTerm, null, 2)};\nexport default ${varName};\n`;
  fs.writeFileSync(fileName, fileContent, 'utf8');
  console.log('Wrote', fileName);
  // collect codes from mergedTerm.courses
  Object.keys(mergedTerm.courses || {}).forEach(c => uniqueCodes.add(c));
}

// regenerate index.js
const indexPath = path.join(outDir, 'index.js');
const imports = termKeys.map(k => `import { ECE_SYLLABUS_${k} } from './${k}.js';`).join('\n');
const termMapEntries = termKeys.map(k => `  ${k}: ECE_SYLLABUS_${k},`).join('\n');
const indexContent = `// AUTO-GENERATED by scripts/generate_ece_syllabus.cjs\n${imports}\n\nconst TERM_SYLLABUS = {\n${termMapEntries}\n};\n\nconst mergeCourses = () => {\n  const all = {};\n  Object.values(TERM_SYLLABUS).forEach(term => { Object.assign(all, term.courses); });\n  return all;\n};\n\nexport const ECE_SYLLABUS = {\n  sourceFile: 'src/data/curriculum/departments/ECE/syllabus/index.js',\n  terms: TERM_SYLLABUS,\n  courses: mergeCourses(),\n};\n\nexport default ECE_SYLLABUS;\n`;
fs.writeFileSync(indexPath, indexContent, 'utf8');
console.log('Wrote', indexPath);

// summary (recompute using merged optionalCourses)
const mergedCounts = termKeys.reduce((acc, k) => {
  const t = terms[k];
  const baseCount = Object.keys(t.courses || {}).length;
  const optionalCount = Array.isArray(t.optionalCourses) ? t.optionalCourses.length : 0;
  acc += baseCount + optionalCount;
  return acc;
}, 0);
console.log('Terms:', termKeys.length, 'Total courses (including optionalCourses):', mergedCounts);
console.log('Unique course codes after merge:', uniqueCodes.size);

process.exit(0);
