const fs = require('fs');
const path = require('path');

const termOrder = ['Y1T1', 'Y1T2', 'Y2T1', 'Y2T2', 'Y3T1', 'Y3T2', 'Y4T1', 'Y4T2'];

const normalizeContactHours = value => {
  if (!value) {
    return value;
  }
  return value.replace(/hrs\/wk/g, 'hrs/week');
};

const normalizeCredit = value => {
  if (value === null || value === undefined) {
    return null;
  }
  const num = Number(value);
  return Number.isFinite(num) ? num : value;
};

const isSessionalCourse = course => {
  const title = String(course.title || '').toLowerCase();
  const keywords = [
    'lab',
    'laboratory',
    'sessional',
    'workshop',
    'practice',
    'practices',
    'project',
    'thesis',
    'training',
    'simulation',
    'seminar'
  ];

  if (keywords.some(keyword => title.includes(keyword))) {
    return true;
  }

  const credit = course.credit;
  if (typeof credit === 'number' && credit <= 1.5) {
    return true;
  }

  const contact = course.contactHour || '';
  if (contact.includes('3/2')) {
    return true;
  }

  return false;
};

const applySessionalDefaults = course => {
  if (!isSessionalCourse(course)) {
    return course;
  }

  const updated = { ...course };
  const normalizedContact = normalizeContactHours(updated.contactHour || null);
  updated.contactHour = normalizedContact;

  if (updated.credit === null || updated.credit === undefined) {
    if (normalizedContact && normalizedContact.includes('3/2')) {
      updated.credit = 0.75;
    } else if (normalizedContact && normalizedContact.includes('3 hrs/week')) {
      updated.credit = 1.5;
    } else {
      updated.credit = 0.75;
    }
  }

  if (!updated.contactHour) {
    updated.contactHour = updated.credit <= 0.75 ? '3/2 hrs/week' : '3 hrs/week';
  }

  return updated;
};

const readJson = inputPath => {
  const raw = fs.readFileSync(inputPath, 'utf8');
  return JSON.parse(raw);
};

const ensureDir = dirPath => {
  fs.mkdirSync(dirPath, { recursive: true });
};

const writeFile = (filePath, content) => {
  fs.writeFileSync(filePath, content, 'utf8');
};

const buildTermsArray = courses => Object.entries(courses).map(([code, course]) => {
  const normalized = applySessionalDefaults(course);
  const contactHours = normalizeContactHours(normalized.contactHour || null);
  const credits = normalizeCredit(normalized.credit);
  return {
    code,
    title: normalized.title,
    credits,
    contactHours,
    type: isSessionalCourse(normalized) ? 'Sessional' : 'Theory',
    isOptional: false
  };
});

const buildOptionalList = terms => {
  const byCode = new Map();
  termOrder.forEach(termKey => {
    const term = terms[termKey];
    if (!term || !Array.isArray(term.optionalCourses)) {
      return;
    }
    term.optionalCourses.forEach(course => {
      const normalized = applySessionalDefaults(course);
      const code = normalized.courseCode;
      if (!code) {
        return;
      }
      if (byCode.has(code)) {
        return;
      }
      const credits = normalizeCredit(normalized.credit);
      const contactHours = normalizeContactHours(normalized.contactHour || null);
      byCode.set(code, {
        code,
        title: normalized.title,
        credits,
        contactHours,
        type: isSessionalCourse(normalized) ? 'Sessional' : 'Theory'
      });
    });
  });
  return Array.from(byCode.values());
};

const buildSyllabusTerm = term => {
  const normalizedCourses = {};
  Object.entries(term.courses).forEach(([code, course]) => {
    const normalized = applySessionalDefaults(course);
    normalizedCourses[code] = {
      title: normalized.title,
      credit: normalizeCredit(normalized.credit),
      contactHour: normalizeContactHours(normalized.contactHour || null),
      topics: Array.isArray(normalized.topics) ? normalized.topics : [],
      sessionalNote: normalized.sessionalNote ?? null,
      references: Array.isArray(normalized.references) ? normalized.references : []
    };
  });

  return {
    termKey: term.termKey,
    title: term.title,
    courses: normalizedCourses,
    optionalCourses: Array.isArray(term.optionalCourses)
      ? term.optionalCourses.map(course => applySessionalDefaults(course))
      : [],
    termNotes: Array.isArray(term.termNotes) ? term.termNotes : []
  };
};

const makeSyllabusIndex = termKeys => {
  const imports = termKeys
    .map(termKey => `import { CHE_SYLLABUS_${termKey} } from './${termKey}.js';`)
    .join('\n');

  const termEntries = termKeys
    .map(termKey => `  ${termKey}: CHE_SYLLABUS_${termKey},`)
    .join('\n');

  return `// AUTO-GENERATED by scripts/generate_che_from_json.cjs\n${imports}\n\nconst TERM_SYLLABUS = {\n${termEntries}\n};\n\nconst mergeCourses = () => {\n  const all = {};\n  Object.values(TERM_SYLLABUS).forEach(term => { Object.assign(all, term.courses); });\n  return all;\n};\n\nexport const CHE_SYLLABUS = {\n  sourceFile: 'src/data/curriculum/departments/ChE/syllabus/index.js',\n  terms: TERM_SYLLABUS,\n  courses: mergeCourses(),\n};\n\nexport default CHE_SYLLABUS;\n`;
};

const makeTermsIndex = termKeys => {
  const imports = termKeys.map(termKey => `import { ${termKey} } from './${termKey}.js';`).join('\n');
  const entries = termKeys.map(termKey => `  ${termKey},`).join('\n');
  return `${imports}\n\nexport const CHE_TERMS = {\n${entries}\n};\n`;
};

const makeDepartmentIndex = () => (
  `import { CHE_META } from './meta.js';\n` +
  `import { CHE_TERMS } from './terms/index.js';\n` +
  `import { CHE_OPTIONAL_COURSES } from './optional.js';\n` +
  `import { CHE_NOTES } from './notes.js';\n` +
  `import { CHE_SYLLABUS } from './syllabus/index.js';\n\n` +
  `export const CHE_DEPARTMENT = {\n` +
  `  meta: CHE_META,\n` +
  `  terms: CHE_TERMS,\n` +
  `  optional: CHE_OPTIONAL_COURSES,\n` +
  `  notes: CHE_NOTES,\n` +
  `  syllabus: CHE_SYLLABUS,\n` +
  `};\n`
);

const main = () => {
  const inputPath = path.resolve('sylla/abc/chemical/che syllabus.json');
  const data = readJson(inputPath);
  const terms = data.terms || {};

  termOrder.forEach(termKey => {
    const term = terms[termKey];
    if (!term || !term.courses) {
      return;
    }

    Object.entries(term.courses).forEach(([code, course]) => {
      term.courses[code] = applySessionalDefaults(course);
    });

    if (Array.isArray(term.optionalCourses)) {
      term.optionalCourses = term.optionalCourses.map(course => applySessionalDefaults(course));
    }
  });

  const outputRoot = path.resolve('src/data/curriculum/departments/ChE');
  const termsDir = path.join(outputRoot, 'terms');
  const syllabusDir = path.join(outputRoot, 'syllabus');

  ensureDir(termsDir);
  ensureDir(syllabusDir);

  const meta = {
    code: 'ChE',
    name: 'Chemical Engineering',
    acronym: 'ChE',
    university: 'Khulna University of Engineering & Technology'
  };

  const notes = {
    overview: 'ChE syllabus generated from provided JSON source.',
    source: 'sylla/abc/chemical/che syllabus.json',
    effectiveFrom: 'unknown'
  };

  const optionalCourses = buildOptionalList(terms);

  writeFile(path.join(outputRoot, 'meta.js'), `export const CHE_META = ${JSON.stringify(meta, null, 2)};\n`);
  writeFile(path.join(outputRoot, 'notes.js'), `export const CHE_NOTES = ${JSON.stringify(notes, null, 2)};\n`);
  writeFile(path.join(outputRoot, 'optional.js'), `export const CHE_OPTIONAL_COURSES = ${JSON.stringify(optionalCourses, null, 2)};\n`);
  writeFile(path.join(outputRoot, 'index.js'), makeDepartmentIndex());

  termOrder.forEach(termKey => {
    const term = terms[termKey];
    if (!term) {
      return;
    }

    const termArray = buildTermsArray(term.courses || {});
    const termPath = path.join(termsDir, `${termKey}.js`);
    writeFile(termPath, `export const ${termKey} = ${JSON.stringify(termArray, null, 2)};\n`);

    const syllabusTerm = buildSyllabusTerm(term);
    const syllabusPath = path.join(syllabusDir, `${termKey}.js`);
    writeFile(
      syllabusPath,
      `export const CHE_SYLLABUS_${termKey} = ${JSON.stringify(syllabusTerm, null, 2)};\nexport default CHE_SYLLABUS_${termKey};\n`
    );
  });

  writeFile(path.join(termsDir, 'index.js'), makeTermsIndex(termOrder));
  writeFile(path.join(syllabusDir, 'index.js'), makeSyllabusIndex(termOrder));
  writeFile(path.join(syllabusDir, 'optional.js'), "export const CHE_SYLLABUS_OPTIONAL = { title: 'Optional', courses: {} };\n");

  writeFile(inputPath, `${JSON.stringify(data, null, 2)}\n`);
};

main();
