const fs = require('fs');
const path = require('path');

const termOrder = ['Y1T1', 'Y1T2', 'Y2T1', 'Y2T2', 'Y3T1', 'Y3T2', 'Y4T1', 'Y4T2'];

const normalizeContactHours = value => {
  if (!value) {
    return value;
  }
  return value.replace(/hrs\/wk/g, 'hrs/week');
};

const normalizeCredit = value => {
  if (value === null || value === undefined) {
    return null;
  }
  const num = Number(value);
  return Number.isFinite(num) ? num : value;
};

const isSessionalCourse = course => {
  const title = String(course.title || '').toLowerCase();
  const keywords = [
    'lab',
    'laboratory',
    'sessional',
    'workshop',
    'practice',
    'practices',
    'drawing',
    'project',
    'thesis',
    'training',
    'seminar'
  ];

  if (keywords.some(keyword => title.includes(keyword))) {
    return true;
  }

  const credit = course.credit;
  if (typeof credit === 'number' && credit <= 1.5) {
    return true;
  }

  const contact = course.contactHour || '';
  if (contact.includes('3/2')) {
    return true;
  }

  return false;
};

const readJson = inputPath => {
  const raw = fs.readFileSync(inputPath, 'utf8');
  return JSON.parse(raw);
};

const ensureDir = dirPath => {
  fs.mkdirSync(dirPath, { recursive: true });
};

const writeFile = (filePath, content) => {
  fs.writeFileSync(filePath, content, 'utf8');
};

const buildTermsArray = courses => Object.entries(courses).map(([code, course]) => {
  const contactHours = normalizeContactHours(course.contactHour || null);
  const credits = normalizeCredit(course.credit);
  return {
    code,
    title: course.title,
    credits,
    contactHours,
    type: isSessionalCourse(course) ? 'Sessional' : 'Theory',
    isOptional: false
  };
});

const buildOptionalList = terms => {
  const byCode = new Map();
  termOrder.forEach(termKey => {
    const term = terms[termKey];
    if (!term || !Array.isArray(term.optionalCourses)) {
      return;
    }
    term.optionalCourses.forEach(course => {
      const code = course.courseCode;
      if (!code || byCode.has(code)) {
        return;
      }
      const credits = normalizeCredit(course.credit);
      const contactHours = normalizeContactHours(course.contactHour || null);
      byCode.set(code, {
        code,
        title: course.title,
        credits,
        contactHours,
        type: isSessionalCourse(course) ? 'Sessional' : 'Theory'
      });
    });
  });
  return Array.from(byCode.values());
};

const buildSyllabusTerm = term => {
  const normalizedCourses = {};
  Object.entries(term.courses).forEach(([code, course]) => {
    normalizedCourses[code] = {
      title: course.title,
      credit: normalizeCredit(course.credit),
      contactHour: normalizeContactHours(course.contactHour || null),
      topics: Array.isArray(course.topics) ? course.topics : [],
      sessionalNote: course.sessionalNote ?? null,
      references: Array.isArray(course.references) ? course.references : []
    };
  });

  return {
    termKey: term.termKey,
    title: term.title,
    courses: normalizedCourses,
    optionalCourses: Array.isArray(term.optionalCourses) ? term.optionalCourses : [],
    termNotes: Array.isArray(term.termNotes) ? term.termNotes : []
  };
};

const makeSyllabusIndex = termKeys => {
  const imports = termKeys
    .map(termKey => `import { CE_SYLLABUS_${termKey} } from './${termKey}.js';`)
    .join('\n');

  const termEntries = termKeys
    .map(termKey => `  ${termKey}: CE_SYLLABUS_${termKey},`)
    .join('\n');

  return `// AUTO-GENERATED by scripts/generate_ce_from_json.cjs\n${imports}\n\nconst TERM_SYLLABUS = {\n${termEntries}\n};\n\nconst mergeCourses = () => {\n  const all = {};\n  Object.values(TERM_SYLLABUS).forEach(term => { Object.assign(all, term.courses); });\n  return all;\n};\n\nexport const CE_SYLLABUS = {\n  sourceFile: 'src/data/curriculum/departments/CE/syllabus/index.js',\n  terms: TERM_SYLLABUS,\n  courses: mergeCourses(),\n};\n\nexport default CE_SYLLABUS;\n`;
};

const makeTermsIndex = termKeys => {
  const imports = termKeys.map(termKey => `import { ${termKey} } from './${termKey}.js';`).join('\n');
  const entries = termKeys.map(termKey => `  ${termKey},`).join('\n');
  return `${imports}\n\nexport const CE_TERMS = {\n${entries}\n};\n`;
};

const makeDepartmentIndex = () => (
  `import { CE_META } from './meta.js';\n` +
  `import { CE_TERMS } from './terms/index.js';\n` +
  `import { CE_OPTIONAL_COURSES } from './optional.js';\n` +
  `import { CE_NOTES } from './notes.js';\n` +
  `import { CE_SYLLABUS } from './syllabus/index.js';\n\n` +
  `export const CE_DEPARTMENT = {\n` +
  `  meta: CE_META,\n` +
  `  terms: CE_TERMS,\n` +
  `  optional: CE_OPTIONAL_COURSES,\n` +
  `  notes: CE_NOTES,\n` +
  `  syllabus: CE_SYLLABUS,\n` +
  `};\n`
);

const main = () => {
  const inputPath = path.resolve('samplesourcejustforreference/abc/civil/ce syllabus.json');
  const data = readJson(inputPath);
  const terms = data.terms || {};

  const outputRoot = path.resolve('src/data/curriculum/departments/CE');
  const termsDir = path.join(outputRoot, 'terms');
  const syllabusDir = path.join(outputRoot, 'syllabus');

  ensureDir(termsDir);
  ensureDir(syllabusDir);

  const meta = {
    code: 'CE',
    name: 'Civil Engineering',
    acronym: 'CE',
    university: 'Khulna University of Engineering & Technology'
  };

  const notes = {
    overview: 'CE syllabus generated from provided JSON source.',
    source: 'samplesourcejustforreference/abc/civil/ce syllabus.json',
    effectiveFrom: 'unknown'
  };

  const optionalCourses = buildOptionalList(terms);

  writeFile(path.join(outputRoot, 'meta.js'), `export const CE_META = ${JSON.stringify(meta, null, 2)};\n`);
  writeFile(path.join(outputRoot, 'notes.js'), `export const CE_NOTES = ${JSON.stringify(notes, null, 2)};\n`);
  writeFile(path.join(outputRoot, 'optional.js'), `export const CE_OPTIONAL_COURSES = ${JSON.stringify(optionalCourses, null, 2)};\n`);
  writeFile(path.join(outputRoot, 'index.js'), makeDepartmentIndex());

  termOrder.forEach(termKey => {
    const term = terms[termKey];
    if (!term) {
      return;
    }

    const termArray = buildTermsArray(term.courses || {});
    const termPath = path.join(termsDir, `${termKey}.js`);
    writeFile(termPath, `export const ${termKey} = ${JSON.stringify(termArray, null, 2)};\n`);

    const syllabusTerm = buildSyllabusTerm(term);
    const syllabusPath = path.join(syllabusDir, `${termKey}.js`);
    writeFile(
      syllabusPath,
      `export const CE_SYLLABUS_${termKey} = ${JSON.stringify(syllabusTerm, null, 2)};\nexport default CE_SYLLABUS_${termKey};\n`
    );
  });

  writeFile(path.join(termsDir, 'index.js'), makeTermsIndex(termOrder));
  writeFile(path.join(syllabusDir, 'index.js'), makeSyllabusIndex(termOrder));
  writeFile(path.join(syllabusDir, 'optional.js'), "export const CE_SYLLABUS_OPTIONAL = { title: 'Optional', courses: {} };\n");
};

main();
