const fs = require('fs');
const path = require('path');

const inputPath = path.resolve('samplesourcejustforreference/becmcurriculmn.json');
const outputRoot = path.resolve('src/data/curriculum/departments/BECM');
const termsDir = path.join(outputRoot, 'terms');
const syllabusDir = path.join(outputRoot, 'syllabus');
const termOrder = ['Y1T1', 'Y1T2', 'Y2T1', 'Y2T2', 'Y3T1', 'Y3T2', 'Y4T1', 'Y4T2'];
const PLACEHOLDER = 'Sorry, we cannot collect only this dept course syllabus. Please help us and contact with founder.';

const ensureDir = dir => fs.mkdirSync(dir, { recursive: true });
const writeFile = (filePath, content) => fs.writeFileSync(filePath, content, 'utf8');
const readJson = input => JSON.parse(fs.readFileSync(input, 'utf8'));

const normalizeContactHours = value => {
  if (value === undefined || value === null || value === '') {
    return null;
  }
  return String(value).replace(/hrs\/wk/gi, 'hrs/week');
};

const normalizeCredit = value => {
  if (value === undefined || value === null || value === '') {
    return null;
  }
  const num = Number(value);
  return Number.isFinite(num) ? num : value;
};

const isSessionalCourse = course => {
  const title = String(course.title || '').toLowerCase();
  if (course.sessionalNote) {
    return true;
  }
  if (typeof course.credit === 'number' && course.credit <= 1.5) {
    return true;
  }
  if (title.includes('sessional') || title.includes('laboratory') || title.includes('lab') || title.includes('drawing') || title.includes('project') || title.includes('seminar') || title.includes('workshop')) {
    return true;
  }
  return false;
};

const makeMeta = data => ({
  code: 'BECM',
  name: 'Building Engineering and Construction Management',
  acronym: 'BECM',
  university: data.university || 'Khulna University of Engineering & Technology',
  effectiveFrom: data.effectiveFrom || '2015-2016',
});

const makeNotes = data => ({
  overview: 'BECM curriculum generated from provided JSON reference with placeholder syllabi for each course.',
  source: 'samplesourcejustforreference/becmcurriculmn.json',
  effectiveFrom: data.effectiveFrom || '2015-2016',
});

const makeTermCourses = courses => Object.entries(courses || {}).map(([code, course]) => ({
  code,
  title: course.title,
  credits: normalizeCredit(course.credit),
  contactHours: normalizeContactHours(course.contactHour),
  type: isSessionalCourse(course) ? 'Sessional' : 'Theory',
  isOptional: false,
}));

const makeSyllabusCourses = courses => {
  const result = {};
  Object.entries(courses || {}).forEach(([code, course]) => {
    const topics = Array.isArray(course.topics) && course.topics.length > 0
      ? course.topics
      : [PLACEHOLDER];

    result[code] = {
      title: course.title,
      credit: normalizeCredit(course.credit),
      contactHour: normalizeContactHours(course.contactHour),
      topics,
      sessionalNote: course.sessionalNote ?? null,
      references: Array.isArray(course.references) ? course.references : [],
    };
  });
  return result;
};

const makeOptionalCourses = data => {
  const groups = data.optionalGroups || {};
  const optionalCourses = [];

  Object.values(groups).forEach(group => {
    Object.values(group || {}).forEach(course => {
      if (!course || typeof course !== 'object') {
        return;
      }
      optionalCourses.push({
        code: course.courseCode || course.code || '',
        title: course.title || '',
        credits: normalizeCredit(course.credit),
        contactHours: normalizeContactHours(course.contactHour),
        type: course.sessionalNote ? 'Sessional' : 'Theory',
        isOptional: true,
      });
    });
  });

  return optionalCourses;
};

const makeTermsIndex = termKeys => {
  const imports = termKeys.map(termKey => `import { ${termKey} } from './${termKey}.js';`).join('\n');
  const entries = termKeys.map(termKey => `  ${termKey},`).join('\n');
  return `${imports}\n\nexport const BECM_TERMS = {\n${entries}\n};\n\nexport default BECM_TERMS;\n`;
};

const makeSyllabusIndex = termKeys => {
  const imports = termKeys.map(termKey => `import { BECM_SYLLABUS_${termKey} } from './${termKey}.js';`).join('\n');
  const entries = termKeys.map(termKey => `  ${termKey}: BECM_SYLLABUS_${termKey},`).join('\n');
  return `// AUTO-GENERATED by scripts/generate_becm_from_json.cjs\n${imports}\n\nconst TERM_SYLLABUS = {\n${entries}\n};\n\nconst mergeCourses = () => {\n  const all = {};\n  Object.values(TERM_SYLLABUS).forEach(term => { Object.assign(all, term.courses); });\n  return all;\n};\n\nexport const BECM_SYLLABUS = {\n  sourceFile: 'src/data/curriculum/departments/BECM/syllabus/index.js',\n  terms: TERM_SYLLABUS,\n  courses: mergeCourses(),\n};\n\nexport default BECM_SYLLABUS;\n`;
};

const makeDepartmentIndex = () => (
  `import { BECM_META } from './meta.js';\n` +
  `import { BECM_TERMS } from './terms/index.js';\n` +
  `import { BECM_OPTIONAL_COURSES } from './optional.js';\n` +
  `import { BECM_NOTES } from './notes.js';\n` +
  `import { BECM_SYLLABUS } from './syllabus/index.js';\n\n` +
  `export const BECM_DEPARTMENT = {\n` +
  `  meta: BECM_META,\n` +
  `  terms: BECM_TERMS,\n` +
  `  optional: BECM_OPTIONAL_COURSES,\n` +
  `  notes: BECM_NOTES,\n` +
  `  syllabus: BECM_SYLLABUS,\n` +
  `};\n\nexport default BECM_DEPARTMENT;\n`
);

const main = () => {
  const data = readJson(inputPath);
  const termsData = data.terms || {};

  ensureDir(outputRoot);
  ensureDir(termsDir);
  ensureDir(syllabusDir);

  const meta = makeMeta(data);
  const notes = makeNotes(data);
  const optionalCourses = makeOptionalCourses(data);

  writeFile(path.join(outputRoot, 'meta.js'), `export const BECM_META = ${JSON.stringify(meta, null, 2)};\nexport default BECM_META;\n`);
  writeFile(path.join(outputRoot, 'notes.js'), `export const BECM_NOTES = ${JSON.stringify(notes, null, 2)};\nexport default BECM_NOTES;\n`);
  writeFile(path.join(outputRoot, 'optional.js'), `export const BECM_OPTIONAL_COURSES = ${JSON.stringify(optionalCourses, null, 2)};\nexport default BECM_OPTIONAL_COURSES;\n`);
  writeFile(path.join(outputRoot, 'index.js'), makeDepartmentIndex());

  termOrder.forEach(termKey => {
    const term = termsData[termKey];
    if (!term) {
      return;
    }

    const termFile = `export const ${termKey} = ${JSON.stringify(makeTermCourses(term.courses || {}), null, 2)};\nexport default ${termKey};\n`;
    writeFile(path.join(termsDir, `${termKey}.js`), termFile);

    const syllabusTerm = {
      termKey: term.termKey,
      title: term.title,
      courses: makeSyllabusCourses(term.courses || {}),
      optionalCourses: Array.isArray(term.optionalCourses) ? term.optionalCourses : [],
      termNotes: Array.isArray(term.termNotes) ? term.termNotes : [],
    };

    const syllabusFile = `export const BECM_SYLLABUS_${termKey} = ${JSON.stringify(syllabusTerm, null, 2)};\nexport default BECM_SYLLABUS_${termKey};\n`;
    writeFile(path.join(syllabusDir, `${termKey}.js`), syllabusFile);
  });

  writeFile(path.join(termsDir, 'index.js'), makeTermsIndex(termOrder));
  writeFile(path.join(syllabusDir, 'index.js'), makeSyllabusIndex(termOrder));

  console.log('BECM curriculum generated successfully.');
};

main();
