#!/usr/bin/env python3
"""Restore archived question papers into public/questions and generate availability overrides."""

from __future__ import annotations

import re
import sys
from pathlib import Path

try:
    import zstandard as zstd
except Exception:
    print('Missing Python dependency: zstandard. Run: pip install zstandard')
    sys.exit(2)

ROOT = Path(__file__).resolve().parents[1]
ARCHIVE_ROOT = ROOT / 'src' / 'data' / 'QUESTION Bank'
PUBLIC_ROOT = ROOT / 'public' / 'questions'
GENERATED_MODULE = ROOT / 'src' / 'data' / 'questionbank' / 'generatedQuestionBankAvailability.js'

DEPT_MAP = {
    'Department of Architecture': 'ARCH',
    'Department of Biomedical Engineering': 'BME',
    'Department of Building Engineering and Construction Management': 'BECM',
    'Department of Civil Engineering': 'CE',
    'Department of Chemical Engineering': 'ChE',
    'Department of Computer Science and Engineering': 'CSE',
    'Department of Electrical and Electronic Engineering': 'EEE',
    'Department of Electronics and Communication Engineering': 'ECE',
    'Department of Energy Science and Engineering': 'ESE',
    'Department of Industrial Engineering and Management': 'IPE',
    'Department of Leather Engineering': 'LE',
    'Department of Materials Science and Engineering': 'MSE',
    'Department of Mechanical Engineering': 'ME',
    'Department of Mechatronics Engineering': 'MTE',
    'Department of Textile Engineering': 'TE',
    'Department of Urban and Regional Planning': 'URP',
}

FILENAME_RE = re.compile(
    r'^(?P<prefix>.+?)(?P<examYear>\d{4})\.{1,2}pdf\.zst$',
    re.IGNORECASE,
)
YEAR_RE = re.compile(r'(?P<year>\d)(?:st|nd|rd|th)\s+Year', re.IGNORECASE)
TERM_RE = re.compile(r'(?P<term>\d)(?:st|nd|rd|th)\s+Term', re.IGNORECASE)


def parse_year(text: str) -> int | None:
    match = YEAR_RE.search(text)
    return int(match.group('year')) if match else None


def parse_term(text: str) -> int | None:
    match = TERM_RE.search(text)
    return int(match.group('term')) if match else None


def restore_zst(source: Path, target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    dctx = zstd.ZstdDecompressor()
    with source.open('rb') as source_fp, target.open('wb') as target_fp:
        dctx.copy_stream(source_fp, target_fp)


def build_output_path(source: Path) -> tuple[str, Path, str] | None:
    try:
        term_folder = source.parents[0].name
        dept_folder = source.parents[1].name
    except IndexError:
        return None

    dept_code = DEPT_MAP.get(dept_folder)
    if not dept_code:
        return None

    match = FILENAME_RE.match(source.name)
    if not match:
        return None

    prefix = match.group('prefix')
    exam_year = match.group('examYear')

    prefix_lower = prefix.lower()
    if 'special backlog' in prefix_lower:
        exam_type = 'Special_Backlog'
    elif 'backlog' in prefix_lower:
        exam_type = 'Backlog'
    elif 'online' in prefix_lower or 'covid-19' in prefix_lower or 'special examination' in prefix_lower:
        exam_type = 'Online'
    else:
        exam_type = 'Regular'

    if term_folder.lower() == 'backlog':
        year = parse_year(prefix) or 0
        term = 0
    else:
        year = parse_year(term_folder)
        term = parse_term(term_folder)

    if year is None or term is None:
        return None

    question_id = f'{dept_code}_Y{year}T{term}_{exam_type}_{exam_year}'
    out_dir = PUBLIC_ROOT / dept_code / f'Y{year}T{term}'
    out_file = out_dir / f'{exam_type}_{exam_year}.pdf'
    return question_id, out_file, dept_folder


def sync() -> None:
    if not ARCHIVE_ROOT.exists():
                raise SystemExit(f'Archive root not found: {ARCHIVE_ROOT}')

    zst_files = sorted(ARCHIVE_ROOT.rglob('*.pdf.zst'))
    if not zst_files:
        raise SystemExit(f'No .pdf.zst files found under {ARCHIVE_ROOT}')

    restored_ids: dict[str, dict[str, bool]] = {}
    restored_count = 0
    skipped_count = 0

    for source in zst_files:
        output = build_output_path(source)
        if not output:
            skipped_count += 1
            continue

        question_id, target_pdf, dept_folder = output
        try:
            restore_zst(source, target_pdf)
            restored_ids[question_id] = {'available': True}
            restored_count += 1
        except Exception as exc:
            skipped_count += 1
            print(f'Failed: {source} -> {exc}')

    GENERATED_MODULE.parent.mkdir(parents=True, exist_ok=True)
    module_lines = [
        '// Auto-generated by scripts/sync_question_bank_assets.py',
        '// Do not edit manually.',
        'export const QB_GENERATED_OVERRIDES = {',
    ]
    for question_id in sorted(restored_ids):
        module_lines.append(f"  '{question_id}': {{ available: true }},")
    module_lines.append('};')
    module_lines.append('')
    GENERATED_MODULE.write_text('\n'.join(module_lines), encoding='utf-8')

    print(f'Restored {restored_count} PDFs to {PUBLIC_ROOT}')
    print(f'Generated {len(restored_ids)} availability overrides at {GENERATED_MODULE}')
    print(f'Skipped {skipped_count} archive files')


if __name__ == '__main__':
    sync()
